### ISSUE TITLE
Binary Load?

### ISSUE THREAD

**Issue by rvaheldendaten** [q2g/q2g-con-hypercube-qvx#19]
Hi!

In more recent documentation Qlik states that BINARY Load on Server Apps is not supported on Qlik Sense Enterprise Servers (Even it has worked in Qlik Sense 3.x). 

> "You cannot use binary to load data from an app on the same Qlik Sense Enterprise deployment by referring to the app ID. " 

https://help.qlik.com/en-US/sense/February2018/Subsystems/Hub/Content/Scripting/ScriptRegularStatements/Binary.htm

I wonder if I can use this connector as a replacement for the Binary Load? Can I do a single statement to retrieve all tables? So even when the underlying datastructure changes, I would like to have all tables loaded without changing the script.

Thx,
Roland

**Comment by konne** [comment]
Hi,

This is not a good binary load statement replacement. It is more designed to fetch an aggregated view of multiple tables with aggregated expressions into a new app.
For binary load, I think you can use our Powershell connector, make an automatic export of the app and use this again as binary datasource.

Bye Konrad

**Comment by rvaheldendaten** [comment]
Hi Konrad!
Thanks for the fast response. That's what I thought so too.

Really wondering why no one is missing the BINARY Load in Qlik Sense. I always thought it is a nice seperation between Datamodellers and Business People.

**Comment by konne** [comment]
Hi,
I don’t know why only some users miss that. I think the main point is the not solved load of master items,,, in this scenarios. I will close that issue.
