### ISSUE TITLE
Sense App Connector not showing any qvf files in the dropdown

### ISSUE THREAD

**Issue by WalterColeman** [q2g/q2g-con-hypercube-qvx#21]
Were running the February 2018 release of Sense, we copied the file contents to the location in the readme. 'C:\Program Files\Common Files\Qlik\Custom Data\'
Downloaded today: 4/25/2018 zip

We stopped & Started the services, what are we missing here?
The drop-down does not show anything!
What other files should be in that location? To verify were in the right place.

**Comment by mossbeard** [comment]
Hi,
sorry for the late answer.
Is your problem with the connector solved?
I have tested this case in the current version (November 2018) of qlik, but it works.

**Comment by mossbeard** [comment]
No answer Will be closed.
If you have any questions please ask for a new issue.
