### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by rgluzman** [q2g/q2g-con-hypercube-qvx#22]
Hello
I have QS June 2018 patch 1
I compile and put files to a directory named 'q2gConHypercubeQVX' into  C:\Program Files\Common Files\Qlik\
But after restarting services I don't have your connector
Do you have any idea please ?
Regards

**Comment by mossbeard** [comment]
@rgluzman Hello,
please copy the connector into the following directory as it should work.
"C:\Program Files\Common Files\Qlik\Custom Data"
![image](https://user-images.githubusercontent.com/26477924/51016498-dbd1f000-1570-11e9-9cbb-fdcf8365c16c.png)

**Comment by mossbeard** [comment]
No response Will be closed.
If you have any questions please make a new issue.
