### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by DankyDuck82** [q2g/q2g-con-hypercube-qvx#44]
HI

Great work, and would be helpful if I can get it to work :) 
Probably it is easy for some people, but my programming skills are the same as a two-year-old flying a plane without both its wings... 

So hopefully you can help this crash pilot. 

I don't have the folder you are referring to in your other post. c:/program files/common files/qlik/custom data/

![image](https://user-images.githubusercontent.com/46792517/51337921-b9683700-1a88-11e9-9dc0-e7bb7f95f013.png)

Only pleace it can find the custom data folder is in the %appdata% section. 

![image](https://user-images.githubusercontent.com/46792517/51337999-f16f7a00-1a88-11e9-8c87-ab36eeb5787a.png)

Also you write very simple in your instruction.

source
Clone the Github Repo
Open the .sln in Visual Studio
Compile

Compile is the same as build, correct? if so, then I get all these errors.  (maybe because the folde location is wrong, i do not know)

![image](https://user-images.githubusercontent.com/46792517/51338077-2da2da80-1a89-11e9-969c-640d01f69d21.png)

**Comment by DankyDuck82** [comment]
A quick explanation of how I screwed up. 

- Downloaded zip-file.
- placed it in %appdata% folder
- unpaced the zip-file
- opened the .sln file in VS now located -> C:\Users\username\AppData\Local\Programs\Common Files\Qlik\Custom Data\q2g-con-hypercube-qvx-master\src
-build the .sln file in VS, and got loads of errors

**Comment by konne** [comment]
@mossbeard please answer @DankyDuck82

**Comment by mossbeard** [comment]
@DankyDuck82 
Hello,
we are currently in the process of creating a new version.
Thank you your note, we have reworked the project folder file again.
I'll let you know this week if we have a new version as Master. 
Alternative you can also download the branch "ChangeProject".
If you have any further questions just let us know.

**Comment by mossbeard** [comment]
@DankyDuck82 
Hi, we have updated the development branch.
Feel free to use it. For any questions we are ready to help.

**Comment by DankyDuck82** [comment]
@mossbeard 
Thank you. I will try it and let you know my results. 

Great work btw :)
